config/routes.rb
Rails.application.routes.draw do
  resources :matches
  resources :games
  resources :updates
  get '/select', to: 'matches#select'
  get '/deselect', to: 'matches#deselect'
  get 'password_resets/new'
  get 'password_resets/edit'
  get '/impro_password', to: 'sessionimpros#pass_perdu'
  get '/impro_passreset', to: 'sessionimpros#pass_reset'
  get '/signup', to: 'users#new'
  get '/signup_impro', to: 'sessionimpros#newuser'
get '/profil_impro', to: 'sessionimpros#edituser'
post '/signup', to: 'users#create'
  root 'apis#index'
  get '/help', to: 'static_pages#help'
  get '/contact', to: 'static_pages#contact'
  get '/about', to: 'static_pages#about'
  get '/login', to: 'session#new'
  get '/home', to: 'static_pages#home'
  get '/login_impro', to: 'sessionimpros#new'
  post '/subscribe', to: 'matches#subscribe'
  post '/login', to: 'session#create'
  delete '/logout', to: 'session#destroy'

  resources :users do
    member do
      get :following, :followers
    end
  end

  get 'graph/index'
  get 'graph/data', :defaults => { :format => 'json' }
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :apis, only: [:create, :show, :destroy, :new, :index, :edit, :update]
end

app/models/api.rb
class Api < ApplicationRecord
  validates :api_name, presence: true
  validates :address, presence: true
  validates :apicture, presence: true
  mount_uploader :apicture, ApictureUploader
  validate :apicture_size

  private

  # Validates the size of an uploaded picture.
  def apicture_size
    if apicture.size > 5.megabytes
      errors.add(:picture, "should be less than 5MB")
    end
  end
end

app/controllers/apis_controller.rb
class ApisController < ApplicationController
  before_action :admin_user, only: [:create, :new, :destroy, :edit, :update]
  before_action :set_api, only:[:edit, :update, :destroy]

  def index
    @apis = Api.all
  end

  def new
    @api = Api.new
  end

  def create
    @api = Api.new(api_params)
    if @api.save
      flash[:info] = "Api created"
      redirect_to root_url
    else
      flash[:info] = "Api not created. issue with parameters"
      render 'new'
    end
  end

  def destroy
    @api.destroy
    flash[:success] = "Api deleted"
    redirect_to root_url
  end

  def edit
  end

  def update
    if @api.update(api_params)
    # success
      flash[:success] = "Api updated"
      redirect_to root_path
    else
      render :edit
    end
  end

  private
  def set_api
    @api = Api.find(params[:id])
  end

  def api_params
    params.require(:api).permit(:api_name, :address, :apicture, :active)
  end
end

app/views/apis/_api.html.erb
<div class="col-md-3">
  <div class="over-button">
    <% if api.active? %>
      <%= link_to api.api_name, api.address, class: 'btn btn-lg btn btn-prim ry button-blue' %>
    <% else %>
      <button type="button" class="btn btn-lg btn-danger" disabled="disabled"><%= api.api_name %></button>
    <% end %>
  </div>
  <% if api.active? %>
    <%= link_to api.address do %>
      <%= image_tag api.apicture.url , :class => "img-rounded img-responsive centered bordered"  if api.apicture? %>
    <% end %>
  <% else %>
      <%= image_tag api.apicture.url , :class => "img-rounded img-responsive centered bordered greyed"  if api.apicture? %>
  <% end %>
  <% if logged_in? && current_user.admin?  %>
    <br>   <%= link_to "delete", api, method: :delete,
      data: { confirm: "You are sure?" } %>
    |   <%= link_to "update", edit_api_path(api)  %>
<% end %>
</div>

app/views/apis/_form.html.erb
<% provide(:title, 'New Api') %>
<h1> <%= yield(:title) %>  </h1>
<%= form_for(@api, url: yield(:url_fall)) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <%= f.label :api_name %>
  <%= f.text_field :api_name, class: 'form-control' %>
  <%= f.label :address %>
  <%= f.text_field :address, class: 'form-control' %>
  <% if yield(:type)== 'new' %>
    <%= f.file_field :apicture, accept: 'image/jpeg, image/gif, image/png' %>
  <% end %>
  <%= f.label :active %>
  <%= f.check_box :active %>
  <%= f.submit yield(:button_text), class: "btn btn-prim ry" %>
<% end %>

app/views/apis/edit.html.erb
<% provide(:title, 'Edit api') %>
<% provide(:url_fall, api_path) %>
<% provide(:button_text, 'Save changes') %>
<% provide(:type, 'edit') %>
<%= render "form" %>

app/views/apis/index.html.erb
<% provide(:title, "Applications") %>
<center>
<% if logged_in? && current_user.admin? %>
    <%= link_to "new", new_api_path, style: 'color: white;', class: ' btn btn-lg button-blue' %>
<% end %>
</center>
</br>

<div class="container-fluid">
  <div class="row">
    <%= render @apis %>
  </div>
</div>

app/views/apis/new.html.erb
<% provide(:title, 'New api') %>
<% provide(:url_fall, apis_path) %>
<% provide(:button_text, 'Create api') %>
<% provide(:type, 'new') %>
<%= render "form" %>