config/routes.rb
Rails.application.routes.draw do
  resources :matches
  resources :games
  resources :updates
  get '/select', to: 'matches#select'
  get '/deselect', to: 'matches#deselect'
  get 'password_resets/new'
  get 'password_resets/edit'
  get '/impro_password', to: 'sessionimpros#pass_perdu'
  get '/impro_passreset', to: 'sessionimpros#pass_reset'
  get '/signup', to: 'users#new'
  get '/signup_impro', to: 'sessionimpros#newuser'
get '/profil_impro', to: 'sessionimpros#edituser'
post '/signup', to: 'users#create'
  root 'apis#index'
  get '/help', to: 'static_pages#help'
  get '/contact', to: 'static_pages#contact'
  get '/about', to: 'static_pages#about'
  get '/login', to: 'session#new'
  get '/home', to: 'static_pages#home'
  get '/login_impro', to: 'sessionimpros#new'
  post '/subscribe', to: 'matches#subscribe'
  post '/login', to: 'session#create'
  delete '/logout', to: 'session#destroy'

  resources :users do
    member do
      get :following, :followers
    end
  end

  get 'graph/index'
  get 'graph/data', :defaults => { :format => 'json' }
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :apis, only: [:create, :show, :destroy, :new, :index, :edit, :update]
end

app/controllers/sessionimpros_controller.rb
class SessionimprosController < ApplicationController
  def new
  end

  def pass_perdu

  end

  def pass_reset
     @user = User.find_by(email: params[:email])
  end
  def newuser
@user = User.new
  end

  def edituser
@user = current_user
  end
end

app/helpers/sessionimpros_helper.rb
module SessionimprosHelper
def impro_admin?(user)
   user.type_id == 2
end
end

app/views/sessionimpros/_form.html.erb
<%= form_for(@user, url: yield(:url_fall) ) do |f| %>


  <%= f.label :name, "Identifiant / Nom d'équipe" %>
  <%= f.text_field :name, class: 'form-control' %>

  <%= f.label :email %>
  <%= f.email_field :email, class: 'form-control' %>

  <%= f.label :password, "Mot de passe" %>
  <%= f.password_field :password, class: 'form-control' %>

  <%= f.label :password_confirmation, "Confirmation" %>
  <%= f.password_field :password_confirmation, class: 'form-control' %>

  <%= f.label :type_id, "Profil" %>
  <%= f.select :type_id,
    options_for_select([["Equipe",3],["Staff",4],["Autre",1]],
                       logged_in? ?  current_user.type_id : 3) %>

                     <%= f.submit yield(:button_text), class: "btn button-red" %>
                   <% end %>

app/views/sessionimpros/edituser.html.erb
<% provide(:url_fall, user_path(current_user)) %>
<% provide(:button_text, 'Enregistrer les modifications') %>
<h1>Modifier profil</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/sessionimpros/new.html.erb
<% provide(:title, "Log in") %>
<br><br>
<h1>Connexion</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(:session, url: login_path) do |f| %>
    <center><b>Renseigner l'email OU le login, et le mot de passe</b></center>
</br>
      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :name, "Login" %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :password, "Mot de passe" %>
      <%= link_to "(mot de passe oublié)", impro_password_path %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :remember_me, class: "checkbox inline" do %>
        <%= f.check_box :remember_me %>
        <span>Enregistrer le mot de passe sur cet ordinateur</span>
      <% end %>

      <%= f.submit "Se connecter", class: "btn button-red" %>
    <% end %>

    <p>Nouvel utilisateur? <%= link_to "S'inscrire", signup_impro_path %></p>
  </div>
</div>

app/views/sessionimpros/newuser.html.erb
<% provide(:url_fall, signup_path) %>
<% provide(:button_text, 'Creer mon utilisateur') %>
<br><br><h1>Creation d'utilisateur</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/sessionimpros/pass_perdu.html.erb
<h1>Réinitilisation du mot de passe</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(:password_reset, url: password_resets_path) do |f| %>
      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.submit "Envoyer", class: "btn button-red" %>
    <% end %>
  </div>
</div>

app/views/sessionimpros/pass_reset.html.erb
<h1>Nouveau mot de passe</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user, url: password_reset_path(params[:id])) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= hidden_field_tag :email, @user.email %>

      <%= f.label :password, 'Mot de passe' %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Enregistrer", class: "btn button-red" %>
    <% end %>
  </div>
</div>