config/routes.rb
Rails.application.routes.draw do
  resources :matches
  resources :games
  resources :updates
  get '/select', to: 'matches#select'
  get '/deselect', to: 'matches#deselect'
  get 'password_resets/new'
  get 'password_resets/edit'
  get '/impro_password', to: 'sessionimpros#pass_perdu'
  get '/impro_passreset', to: 'sessionimpros#pass_reset'
  get '/signup', to: 'users#new'
  get '/signup_impro', to: 'sessionimpros#newuser'
get '/profil_impro', to: 'sessionimpros#edituser'
post '/signup', to: 'users#create'
  root 'apis#index'
  get '/help', to: 'static_pages#help'
  get '/contact', to: 'static_pages#contact'
  get '/about', to: 'static_pages#about'
  get '/login', to: 'session#new'
  get '/home', to: 'static_pages#home'
  get '/login_impro', to: 'sessionimpros#new'
  post '/subscribe', to: 'matches#subscribe'
  post '/login', to: 'session#create'
  delete '/logout', to: 'session#destroy'

  resources :users do
    member do
      get :following, :followers
    end
  end

  get 'graph/index'
  get 'graph/data', :defaults => { :format => 'json' }
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :apis, only: [:create, :show, :destroy, :new, :index, :edit, :update]
end

app/models/update.rb
class Update < ApplicationRecord
end

app/controllers/updates_controller.rb
class UpdatesController < ApplicationController
  before_action :admin_user, only: [:show, :edit, :update, :destroy, :new, :create]
  before_action :set_update, only: [:show, :edit, :update, :destroy]

  # GET /updates
  # GET /updates.json
  def index
    @updates = Update.all
  end

  # GET /updates/1
  # GET /updates/1.json
  def show
  end

  # GET /updates/new
  def new
    @update = Update.new
  end

  # GET /updates/1/edit
  def edit
  end

  # POST /updates
  # POST /updates.json
  def create
    @update = Update.new(update_params)

    respond_to do |format|
      if @update.save
        format.html { redirect_to updates_url, notice: 'Update was successfully created.' }
        format.json { render :index, status: :created, location: @update }
      else
        format.html { render :new }
        format.json { render json: @update.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /updates/1
  # PATCH/PUT /updates/1.json
  def update
      if @update.update(update_params)
        redirect_to updates_path
      else
        render :edit
      end
  end

  # DELETE /updates/1
  # DELETE /updates/1.json
  def destroy
    @update.destroy
    respond_to do |format|
      format.html { redirect_to updates_url, notice: 'Update was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_update
      @update = Update.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def update_params
      params.require(:update).permit(:detail, :status)
    end
end

app/helpers/updates_helper.rb
module UpdatesHelper
end

app/views/updates/_form.html.erb
<%= form_for(update) do |f| %>
  <% if update.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(update.errors.count, "error") %> prohibited this update from being saved:</h2>

      <ul>
      <% update.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :detail %>
    <%= f.text_area :detail %>
  </div>

  <div class="field">
    <%= f.label :status %>
    <%= f.select :status, [["Not sarted", 0],["Ongoing",1],["Suspended",2],["Finished",3]] %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/updates/edit.html.erb
<h1>Editing Update</h1>

<%= render 'form', update: @update %>

<%= link_to 'Show', @update %> |
<%= link_to 'Back', updates_path %>

app/views/updates/index.html.erb
<center>
  <% if logged_in? && current_user.admin? %>
    <%= link_to "new", new_update_path, style: 'color: white    ;', class: ' btn btn-lg button-blue' %>

  <% end %>

  <h1 class= "green_row">
    Updates planed for next versions
  </h1>
  <%= image_tag("legende.png") %>
</center>
<div class="table-responsive">
  <table class="table table-striped">
    <tr class="warning">
      <th>Detail</th>
      <th>Status</th>
      <% if logged_in? && current_user.admin? %>
        <th>Edit</th>
        <th>Delete</th>
      <% end %>
    </tr>

    <tbody>
      <% @updates.each do |update| %>
        <tr>
          <td><%= update.detail %></td>
          <td><%= image_tag(update.status.to_s+".png", :alt => update.status)  %></td>
          <% if logged_in? && current_user.admin? %>
            <td><%= link_to 'Edit', edit_update_path(update) %></td>
            <td><%= link_to 'Destroy', update, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/updates/new.html.erb
<h1>New Update</h1>

<%= render 'form', update: @update %>

<%= link_to 'Back', updates_path %>

app/views/updates/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Detail:</strong>
  <%= @update.detail %>
</p>

<p>
  <strong>Status:</strong>
  <%= @update.status %>
</p>

<%= link_to 'Edit', edit_update_path(@update) %> |
<%= link_to 'Back', updates_path %>