config/routes.rb
Rails.application.routes.draw do
  resources :matches
  resources :games
  resources :updates
  get '/select', to: 'matches#select'
  get '/deselect', to: 'matches#deselect'
  get 'password_resets/new'
  get 'password_resets/edit'
  get '/impro_password', to: 'sessionimpros#pass_perdu'
  get '/impro_passreset', to: 'sessionimpros#pass_reset'
  get '/signup', to: 'users#new'
  get '/signup_impro', to: 'sessionimpros#newuser'
get '/profil_impro', to: 'sessionimpros#edituser'
post '/signup', to: 'users#create'
  root 'apis#index'
  get '/help', to: 'static_pages#help'
  get '/contact', to: 'static_pages#contact'
  get '/about', to: 'static_pages#about'
  get '/login', to: 'session#new'
  get '/home', to: 'static_pages#home'
  get '/login_impro', to: 'sessionimpros#new'
  post '/subscribe', to: 'matches#subscribe'
  post '/login', to: 'session#create'
  delete '/logout', to: 'session#destroy'

  resources :users do
    member do
      get :following, :followers
    end
  end

  get 'graph/index'
  get 'graph/data', :defaults => { :format => 'json' }
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :apis, only: [:create, :show, :destroy, :new, :index, :edit, :update]
end

app/models/match.rb
class Match < ApplicationRecord
  has_many :adversaires, dependent: :destroy
  has_many :representants, dependent: :destroy
  has_many :juries, dependent: :destroy
  has_many :arbitres, dependent: :destroy
  has_many :mcs, dependent: :destroy
  has_many :musiques, dependent: :destroy
  belongs_to :organisateur, class_name: 'User', foreign_key: 'orga'
validates :date, presence: true
validates :orga, presence: true
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
  before_action :set_match, only: [:show, :edit, :update, :destroy]
  before_action :logged_in_user, only: [:edit, :update, :new, :create, :destroy, :subscribe]
  before_action :correct_user_or_admin_impro, only: [ :edit, :update, :destroy]
before_action :admin_impro, only: [:create]
  # GET /matches
  # GET /matches.json
  def index
    @matches = Match.all.sort_by &:date
    if logged_in?
      @feed_items = current_user.tags("#improvisades").paginate(page: params[:page])
      @micropost  = current_user.microposts.build
    end
  end

  # GET /matches/1
  # GET /matches/1.json
  def show
  end

  # GET /matches/new
  def new
    @match = Match.new
  end

  # GET /matches/1/edit
  def edit
  end

  # POST /matches
  # POST /matches.json
  def create
    @match = Match.new(match_params)

    respond_to do |format|
      if @match.save
        format.html { redirect_to matches_url, notice: 'Match créé avec succès' }
        format.json { render :index, status: :created, location: @match }
      else
        format.html { render :new }
        format.json { render json: @match.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /matches/1
  # PATCH/PUT /matches/1.json
  def update
    respond_to do |format|
      if @match.update(match_params)
        format.html { redirect_to matches_url, notice: 'Match modifié avec succès' }
        format.json { render :index, status: :ok, location: @match }
      else
        format.html { render :edit }
        format.json { render json: @match.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /matches/1
  # DELETE /matches/1.json
  def destroy
    @match.destroy
    respond_to do |format|
      format.html { redirect_to matches_url, notice: 'Match supprimé' }
      format.json { head :no_content }
    end
  end

  def select
    # on récupère les paramètres de classe, user et match et on règle "selected"
    @objet = params["class"].constantize.find_by(user_id: params["user_id"], match_id: params["match_id"])
    @objet.selected = 1
    @objet.save
    redirect_to matches_url
  end

  def deselect
    # on récupère les paramètres de classe, user et match et on règle "selected"
    @objet = params["class"].constantize.find_by(user_id: params["user_id"], match_id: params["match_id"])
    @objet.selected = 0
    @objet.save
    redirect_to matches_url
  end

  def subscribe
    #pour simplifier la gestion des paramètre : on supprime tout les liens du user et on les remet
    ##
    Adversaire.where(:user_id => current_user.id, :selected => 0).destroy_all
    Musique.where(:user_id => current_user.id, :selected => 0).destroy_all
    Arbitre.where(:user_id => current_user.id, :selected => 0).destroy_all
    Mc.where(:user_id => current_user.id, :selected => 0).destroy_all
    Jury.where(:user_id => current_user.id, :selected => 0).destroy_all
    Representant.where(:user_id => current_user.id, :selected => 0).destroy_all
    #
    #
    #décomposer le résultat du formulaire ici. On récupère la première partie du nom de la checkbox pour obtenir le type, puis on cherche le croisement entre le user id et l'objet id. On l'ajoute s'il existe pas et qu'on a 1 dans la checkbox, et on l'enlève sinon
    #pour checkbox = adversaire_XX = YY
    #@objet = Adversaire.find_by user_id:@current_user, match_id: XX

    #if YY = "on"
    #   if objet?
    #   else
    #      Adversaire.new(match_id: XX, user_id: @current_user, selected: 0)
    #   end
    #else
    #   @objet.destroy if @objet?
    #   end
    params.each do |param, value|
      if value == "on"
        # param => typeobjet_numero
        @parampl = param.split('_')
        @type = @parampl[0]
        @number = @parampl[1]
        #constantize transforme un string en la classe correspondante (si elle existe), mais il faut d'abord ajouter une majuscule à la variable
        @objet = @type.capitalize.constantize.find_by user_id: current_user.id, match_id: @number
        @newrecord = @type.capitalize.constantize.new(match_id: @number, user_id: current_user.id, selected: 0)
        @newrecord.save
      end
    end
    redirect_to matches_url, notice: 'Inscriptions envoyée aux improvisades. Vous recevrez un mail de confirmation de la part des Improvisades'
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_match
    @match = Match.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def match_params
    params.require(:match).permit(:date, :salle, :ville, :orga, :metro, :comment)
  end
  def correct_user_or_admin_impro
    @match = Match.find(params[:id])
    @user = @match.organisateur
    redirect_to('/matchs') unless current_user?(@user)||impro_admin?(current_user)
  end
  def admin_impro
    redirect_to('/matchs') unless impro_admin?(current_user)
  end
end

app/helpers/matches_helper.rb
module MatchesHelper

def jour(date)
   @jour = "Lu " if date.wday == 1
   @jour = "Ma " if date.wday == 2
   @jour = "Me " if date.wday == 3
   @jour = "Je " if date.wday == 4
   @jour = "Ve " if date.wday == 5
   @jour = "Sa " if date.wday == 6
   @jour = "Di " if date.wday == 0
   @jour += date.mday.to_s
   @jour
end

def mois(date)
   @mois = "JANVIER" if date.mon ==1
   @mois = "FEVRIER" if date.mon ==2
   @mois = "MARS" if date.mon ==3
   @mois = "AVRIL" if date.mon ==4
   @mois = "MAI" if date.mon ==5
   @mois = "JUIN" if date.mon ==6
   @mois = "JUILLET" if date.mon ==7
   @mois = "AOUT" if date.mon ==8
   @mois = "SEPTEMBRE" if date.mon ==9
   @mois = "OCTOBRE" if date.mon ==10
   @mois = "NOVEMBRE" if date.mon ==11
   @mois = "DECEMBRE" if date.mon ==12
   @mois
end

  def is_selected?(objet_class, match_id)
objet_class.constantize.where(:match_id => match_id, :selected => 1).present?
  end

def selected_final(objet_class, match_id)
@html =''
@objet = objet_class.constantize.where(:match_id => match_id, :selected => 1)
if @objet.present?
 @objet.each do |objet|
   @html += '<b>' + objet.user.name + '</b></br>'
 end
end
raw @html
end


  def selected_list(objet_class, match_id)
    @one = 0
    @html = ''
    @objet = objet_class.constantize.where(:match_id => match_id)
    if @objet.present?
      @objet.each do |objet|
        if objet.selected ==1
          @html += '<b>'
          @one = 1
        end
        @html +=  objet.user.name
        if objet.selected ==1
          @html += ' </b>'
        end
        @html += '<br/>'
        if logged_in? && impro_admin?(current_user)
          if objet.selected == 0
            @html += link_to "selectionner", select_path(:user_id => objet.user.id, :match_id => match_id, :class => objet_class)
          else
            @html += link_to "enlever", deselect_path(:user_id => objet.user.id, :match_id => match_id, :class => objet_class)
          end
          @html += '<br/>'
        end
      end
      if @one ==1
        @html = '<td class="match">'+@html+'</td>'
      else
        @html = '<td>'+ @html+ '</td>'
      end
    else
      @html += "<td>Pas encore d'inscrits</td>"
    end
    raw @html
  end
end

app/views/matches/_form.html.erb
<%= form_for(match) do |f| %>
  <!-- <%= render 'shared/error_messages', object: f.object %>-->
  <% if match.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(match.errors.count, "erreur") %> empèche la création de ce match:</h2>

      <ul>
      <% match.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>



    <%= f.label :salle %>
    <%= f.text_field :salle, class: 'form-control' %>

    <%= f.label :ville, "Adresse" %>
    <%= f.text_field :ville , class: 'form-control'%>

    <%= f.label :metro, "Transports (Métro/RER/Bus)" %>
    <%= f.text_field :metro , class: 'form-control'%>


    <%= f.label :date %>
    <%= f.text_field :date, :value => yield(:formate), 'data-behaviour' => 'datepicker' , class: 'form-control'%>
    <% if impro_admin?(current_user) %>
    <%= f.label :orga, "Organisateur" %>
    <%= f.collection_select :orga, User.all, :id, :name  %>
    <%= f.label :comment, "Commentaire" %>
    <%= f.text_field :comment, class: 'form-control' %>


  <% end %>
    <%= f.submit yield(:button_text), class: "btn button-red" %>

<% end %>

    <script type="text/javascript">
$('[data-behaviour~=datepicker]').datepicker({
    format: 'dd/mm/yyyy',
    language: 'fr',
    todayHighlight: true,
    todayBtn: "linked"
} );
    </script>

app/views/matches/edit.html.erb
<% provide(:button_text, 'Modifier match')%>
<% provide(:formate, @match.date.strftime("%d/%m/%Y"))%>
<h1>Modifier un match</h1>
<center>
  <b>Attention : pensez à prévenir les Improvisades en cas de changement de date si une équipe a déja été prévue pour ce match</b>
</center>
<br>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form', match: @match %>

    <%= link_to 'Back', matches_path %>
  </div>
</div>

app/views/matches/index.html.erb
<div class="container-fluid">
  <div class="row fire-text">
    <h1>Calendrier Improvisades</h1>
  </div>
  <div class="row">
    <%= form_tag "/subscribe", method: "post" do %>
      <table class="table table-responsive table-striped calendar">
        <thead>
          <tr>
            <th colspan=6 class="match">MATCH</th>
            <th colspan=7 class="part">PARTICIPANTS</th>
            <% if logged_in? %>
              <th colspan=2>EDITER DATES</th>
            <% end %>
            <tr>
              <th class="match">Mois</th>
              <th class="match">Date</th>
              <th class="match">Salle</th>
              <th class="match">Détails</th>
              <th class="match">Adresse</th>
              <th class="match">Transports</th>
              <th class="part">Organisateur</th>
              <th class="part">Invité</th>
              <th class="part">Jury</th>
              <th class="part">Musicien</th>
              <th class="part">Arbitre</th>
              <th class="part">Maître de cérémonie</th>
              <th class="part">Envoyé Improvisades</th>
              <% if logged_in? %>
                <th colspan="2"></th>
              <% end %>
            </tr>
        </thead>

        <tbody>

          <% @matches.each do |match| %>
            <% if logged_in? %>
              <% @adv = @jur = @mus = @arb = @mc = @rep =  '' %>
              <% @adv="checked" if Adversaire.find_by user_id: current_user.id, match_id: match.id %>
              <% @jur="checked" if Jury.find_by user_id: current_user.id, match_id: match.id %>
              <% @mus="checked" if Musique.find_by user_id: current_user.id, match_id: match.id %>
              <% @arb="checked" if Arbitre.find_by user_id: current_user.id, match_id: match.id %>
              <% @mc="checked" if Mc.find_by user_id: current_user.id, match_id: match.id %>
              <% @rep="checked" if Representant.find_by user_id: current_user.id, match_id: match.id %>
            <% end %>
            <tr>
              <td><b><%= mois(match.date) %></b></td>
              <td><%= jour(match.date) %></td>
              <td><%= match.salle %></td>
              <td><%= match.comment %></td>
              <td><%= match.ville %></td>
              <td><%= match.metro %></td>
              <td><%= match.organisateur.name %></td>
              <% if logged_in? &&  impro_admin?(current_user)%>
                <%= selected_list("Adversaire", match.id) %>
              <% end %>
              <% if (logged_in? && !impro_admin?(current_user)) || !logged_in?  %>
                <td>
                  <% if logged_in? && !is_selected?("Adversaire",match.id) && current_user.type_id == 3 %>
                    <input type="checkbox" name="adversaire_<%= match.id %>" <%= @adv%>/>
                  <% else %>
                    <%= selected_final("Adversaire",match.id)%>
                  <% end %>
                </td>

              <% end %>
              <% if logged_in? && impro_admin?(current_user) %>
                <%= selected_list("Jury", match.id) %>
              <% end %>
              <% if (logged_in? && !impro_admin?(current_user)) || !logged_in?  %>
                <td>
                  <% if logged_in?  %>
                    <input type="checkbox" name="jury_<%= match.id %>" <%= @jur%>/>
                  <% else %>
                    <%= selected_final("Jury",match.id)%>
                  <% end %>
                </td>
              <% end %>
              <% if logged_in? && impro_admin?(current_user) %>
                <%= selected_list("Musique", match.id) %>
              <% end %>
              <% if (logged_in? && !impro_admin?(current_user)) || !logged_in?  %>
                <td>
                  <% if logged_in? && current_user.type_id == 4  %>
                    <input type="checkbox" name="musique_<%= match.id %>" <%= @mus%>/>
                  <% else %>
                    <%= selected_final("Musique",match.id)%>
                  <% end %>
                </td>
              <% end %>
              <% if logged_in? && impro_admin?(current_user) %>
                <%= selected_list("Arbitre", match.id) %>
              <% end %>
              <% if (logged_in? && !impro_admin?(current_user)) || !logged_in?  %>
                <td>
                  <% if logged_in? && current_user.type_id == 4 %>
                    <input type="checkbox" name="arbitre_<%= match.id %>" <%= @arb%>/>
                  <% else %>
                    <%= selected_final("Arbitre",match.id)%>
                  <% end %>
                </td>
              <% end %>
              <% if logged_in? && impro_admin?(current_user) %>
                <%= selected_list("Mc", match.id) %>
              <% end %>
              <% if (logged_in? && !impro_admin?(current_user)) || !logged_in?  %>
                <td>
                  <% if logged_in? && current_user.type_id == 4 %>
                    <input type="checkbox" name="mc_<%= match.id %>" <%= @mc%>/>
                  <% else %>
                    <%= selected_final("Mc",match.id)%>
                  <% end %>
                </td>
              <% end %>
              <% if logged_in? && impro_admin?(current_user) %>
                <%= selected_list("Representant", match.id) %>
              <% end %>
              <% if (logged_in? && !impro_admin?(current_user)) || !logged_in?  %>
                <td>
                  <% if logged_in? && current_user.type_id == 4 %>
                    <input type="checkbox" name="representant_<%= match.id %>" <%= @rep%>/>
                  <% else %>
                    <%= selected_final("Representant",match.id)%>
                  <% end %>
                </td>
              <% end %>
              <% if logged_in? && (impro_admin?(current_user) || current_user == match.organisateur) %>
                <td><%= link_to 'Modifier', edit_match_path(match) %></td><% end %>
            <% if logged_in? && impro_admin?(current_user) %>
              <td><%= link_to 'Supprimer', match, method: :delete, data: { confirm: 'Are you sure?' } %></td> <% end %>
        </tr>
      <% end %>
        </tbody>
      </table>
  </div>
  <% if !(logged_in? && !impro_admin?(current_user) )
       @visib_inscr = 'cache'
  end
%>
  <div class= "row">
    <div class="col-md-6">
      <input type="submit" value="Enregistrer les inscriptions" class="btn button-red <%= @visib_inscr %>"     />
    </div>
    <div class="col-md-6"><% if logged_in? && impro_admin?(current_user)%>
      <%= link_to 'Proposer une date', new_match_path, class: "btn button-red" %>
    <% end %>
    </div>
  </div>
<% end %>
  <% if logged_in? %>
   <div class = "col-md-12" id="comments">
    <h3> Commentaires </h3>
    <%= render 'shared/micropost_form_fr' %>
    <%= render 'shared/feed_fr' %>
      </div>

  <% end %>

app/views/matches/new.html.erb
<% provide(:button_text, 'Créer match') %>
<% provide(:formate, "")%>
<h1>Proposer un match</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">

    <%= render 'form', match: @match %>
<%= link_to 'Back', matches_path %>
  </div>
</div>

app/views/matches/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date:</strong>
  <%= @match.date %>
</p>

<p>
  <strong>Salle:</strong>
  <%= @match.salle %>
</p>

<p>
  <strong>Ville:</strong>
  <%= @match.ville %>
</p>

<p>
  <strong>Orga:</strong>
  <%= @match.organisateur.name %>
</p>

<%= link_to 'Edit', edit_match_path(@match) %> |
<%= link_to 'Back', matches_path %>